### ISSUE TITLE
Inconsistencies in the values shown in Show Total Cash Help and Collect Cash.

### ISSUE THREAD

**Issue by sugikushal** [SharanyaMenon/vcms-before#1]
Steps to Reproduce:
1)	Compile and run 
2)	Click on Begin Simulation
3)	Click on Activate Maintainer Panel
4)	Enter the password – 654321
5)	Click on Show Total Cash Held
 
![showtotcashheld](https://user-images.githubusercontent.com/37141821/45614979-cacf1180-ba9d-11e8-9257-d1611a501328.png)

6)	Click on Press to Collect All Cash

![image](https://user-images.githubusercontent.com/37141821/45615031-f3efa200-ba9d-11e8-94bf-3a9c9f15ca54.png)

7)	Click on Activate Machinery Panel
8)	Set the check Box Door Locked to true
9)	Click Press Here When Finished in Maintenance Panel

![image](https://user-images.githubusercontent.com/37141821/45615072-141f6100-ba9e-11e8-864e-8bdfc048af04.png)

10)	Again, enter the password in Maintenance Panel.
![image](https://user-images.githubusercontent.com/37141821/45615088-213c5000-ba9e-11e8-8cb3-6b17c0627563.png)
11)	The values beside Show Total Cash Held and Collect Cash are not Reset/Set to Null.

**Comment by kirioxiangmeow** [comment]
By analyzing, I found that there should be changes made to this file: MaintenanceController.java.
@lucy1994lucy Project Manager please approve this.

**Comment by lucy1994lucy** [comment]
Changes approved.
Assignning bug to @SharanyaMenon

**Comment by SharanyaMenon** [comment]
Issue 1 is fixed and merged to the branch develop_v1. Assigning to the tester to verify

**Comment by sugikushal** [comment]
Issue is verified in latest build of develop_v1. Screenshots attached.
![fixed](https://user-images.githubusercontent.com/37141821/45619996-e17d6480-baad-11e8-94d4-bf2ce0a263e7.png)
Hence, closing the issue.
