### ISSUE TITLE
New Enhancement: To show the denomination

### ISSUE THREAD

**Issue by lucy1994lucy** [SharanyaMenon/vcms-before#3]
**The problem:** It is found that what has been recorded by the system often does not always tally with what the Maintainer submits as collected

**Enhancement Needed :**
This enhancement is needed to aid the Maintainer. 
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer.
This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show
Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute
over system errors.

**_(I am raising this as a Project Manager)_**

**Comment by lucy1994lucy** [comment]
Assigning to @kirioxiangmeow  (Tech Lead)

**Comment by kirioxiangmeow** [comment]
As a **Tech Lead**, I have determined the affected Sequence flows, which are :
- Display Total Cash
- Update Coin Display
- Transfer All cash
- Maintanence Panel

**Comment by kirioxiangmeow** [comment]
Assigning to **@kirioxiangmeow** (Analyst)

**Comment by kirioxiangmeow** [comment]
As an **Analyst**, I have analysed and found the following files which needs changes:
- CoinDisplay.java
- CoinLabelItem.java
- CoinLabelItemDisplay.java
- MaintenanceController.java
- MaintenancePanel.java
- StoreController.java
- TotalCashButtonListener.java

In DMR, Object Specification Affected are :

- Coin Display
- Store Controller
- Maintenance Controller
- Maintenance Panel
- CoinLabelItem	
- CoinLabelItemDisplay

**Comment by kirioxiangmeow** [comment]
Assigning to @sugikushal (Developer)

**Comment by kirioxiangmeow** [comment]
Reviewed and merged to develop_v1.

**Comment by sugikushal** [comment]
Enhancement has been implemented and merged to develop_v1.
@sugikushal (QA) please test and verify.
assigning to @sugikushal

**Comment by sugikushal** [comment]
As a **Tester** I verified the enhancement and it is working fine. Screenshots attached.
Also verified the document.

![totcashheld](https://user-images.githubusercontent.com/37141821/45744384-051ce800-bc31-11e8-91a4-537201e53b4b.jpeg)
![collectcash](https://user-images.githubusercontent.com/37141821/45744398-09490580-bc31-11e8-9531-7f0cdf2fbf70.jpeg)

**Comment by sugikushal** [comment]
Assigning to @lucy1994lucy(**User Representative**)

**Comment by lucy1994lucy** [comment]
I have verified the enhancements. It works as expected.

**Comment by lucy1994lucy** [comment]
Assigning to @SharanyaMenon **(Configuration Manager)**

**Comment by SharanyaMenon** [comment]
Merged develop_v1 to master.

**Comment by SharanyaMenon** [comment]
Released Version R1.0.9 from master. 
Assigning to @lucy1994lucy **(Project Manager)** to close the issue

**Comment by lucy1994lucy** [comment]
Released and hence closing the issue.
